[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build",
    "cmake",
    "ninja; platform_system!='Windows'",
    "numpy",
    "Cython<3.0",
]
build-backend = "setuptools.build_meta"
